"""Reusable Cell Painting workflow wrapper library."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__version__ = '0.1.0'

__all__ = [
    '__version__',
    'CellProfilerConfig',
    'ConfigContractError',
    'DataAccessConfig',
    'ProjectConfig',
    'cellprofiler_config_field_guide',
    'project_config_field_guide',
    'data_access_config_field_guide',
    'project_config_contract_summary',
    'available_cppipe_templates',
    'cppipe_template_definition_to_dict',
    'cppipe_validation_result_to_dict',
    'get_cppipe_template',
    'resolve_cppipe_selection',
    'resolved_cppipe_selection_to_dict',
    'validate_cppipe_configuration',
    'deepprofiler_pipeline_result_to_dict',
    'run_deepprofiler_pipeline',
    'browse_quilt_package',
    'build_data_access_status',
    'build_data_request',
    'build_download_plan',
    'cache_gallery_listing',
    'cpgdata_prefix_list_result_to_dict',
    'cpgdata_sync_result_to_dict',
    'data_access_summary_to_dict',
    'data_download_execution_result_to_dict',
    'data_download_plan_to_dict',
    'data_request_to_dict',
    'download_gallery_prefix',
    'download_gallery_source',
    'execute_download_plan',
    'list_cpgdata_prefixes',
    'list_gallery_datasets',
    'list_gallery_prefixes',
    'list_gallery_sources',
    'list_quilt_packages',
    'load_download_plan',
    'quilt_package_browse_result_to_dict',
    'quilt_package_list_result_to_dict',
    'available_deepprofiler_modes',
    'available_mcp_tools',
    'get_mcp_tool_definition',
    'mcp_tool_catalog',
    'mcp_tool_definition_to_dict',
    'run_mcp_tool',
    'run_mcp_tool_to_dict',
    'create_mcp_server',
    'run_mcp_server',
    'PublicApiContractError',
    'available_public_api_entrypoints',
    'available_public_api_output_contracts',
    'get_public_api_entrypoint',
    'get_public_api_output_contract',
    'public_api_contract_summary',
    'public_api_output_contract_summary',
    'public_api_entrypoint_to_dict',
    'recommended_public_api_pathways',
    'run_public_api_entrypoint',
    'run_public_api_entrypoint_to_dict',
    'available_pipeline_presets',
    'available_pipeline_skills',
    'get_pipeline_skill_definition',
    'pipeline_skill_definition_to_dict',
    'pipeline_skill_result_to_dict',
    'PipelineSkillResult',
    'run_pipeline_skill',
    'get_pipeline_preset_definition',
    'pipeline_preset_definition_to_dict',
    'run_pipeline_preset',
    'end_to_end_pipeline_result_to_dict',
    'resolve_segmentation_suite',
    'run_end_to_end_pipeline',
    'run_deepprofiler_full_stack',
    'run_full_pipeline',
    'run_profiling_suite',
    'run_segmentation_bundle',
    'run_segmentation_suite',
    'run_smoke_test',
    'run_workflow',
    'summarize_data_access',
    'sync_cpgdata_index',
    'sync_cpgdata_inventory',
    'write_download_plan',
]

_EXPORTS: dict[str, tuple[str, str]] = {
    'CellProfilerConfig': ('cellpaint_pipeline.config', 'CellProfilerConfig'),
    'ConfigContractError': ('cellpaint_pipeline.config', 'ConfigContractError'),
    'DataAccessConfig': ('cellpaint_pipeline.config', 'DataAccessConfig'),
    'ProjectConfig': ('cellpaint_pipeline.config', 'ProjectConfig'),
    'cellprofiler_config_field_guide': ('cellpaint_pipeline.config', 'cellprofiler_config_field_guide'),
    'project_config_field_guide': ('cellpaint_pipeline.config', 'project_config_field_guide'),
    'data_access_config_field_guide': ('cellpaint_pipeline.config', 'data_access_config_field_guide'),
    'project_config_contract_summary': ('cellpaint_pipeline.config', 'project_config_contract_summary'),
    'available_cppipe_templates': ('cellpaint_pipeline.cppipe', 'available_cppipe_templates'),
    'cppipe_template_definition_to_dict': ('cellpaint_pipeline.cppipe', 'cppipe_template_definition_to_dict'),
    'cppipe_validation_result_to_dict': ('cellpaint_pipeline.cppipe', 'cppipe_validation_result_to_dict'),
    'get_cppipe_template': ('cellpaint_pipeline.cppipe', 'get_cppipe_template'),
    'resolve_cppipe_selection': ('cellpaint_pipeline.cppipe', 'resolve_cppipe_selection'),
    'resolved_cppipe_selection_to_dict': ('cellpaint_pipeline.cppipe', 'resolved_cppipe_selection_to_dict'),
    'validate_cppipe_configuration': ('cellpaint_pipeline.cppipe', 'validate_cppipe_configuration'),
    'deepprofiler_pipeline_result_to_dict': ('cellpaint_pipeline.deepprofiler_pipeline', 'deepprofiler_pipeline_result_to_dict'),
    'run_deepprofiler_pipeline': ('cellpaint_pipeline.deepprofiler_pipeline', 'run_deepprofiler_pipeline'),
    'browse_quilt_package': ('cellpaint_pipeline.data_access', 'browse_quilt_package'),
    'build_data_access_status': ('cellpaint_pipeline.data_access', 'build_data_access_status'),
    'build_data_request': ('cellpaint_pipeline.data_access', 'build_data_request'),
    'build_download_plan': ('cellpaint_pipeline.data_access', 'build_download_plan'),
    'cache_gallery_listing': ('cellpaint_pipeline.data_access', 'cache_gallery_listing'),
    'cpgdata_prefix_list_result_to_dict': ('cellpaint_pipeline.data_access', 'cpgdata_prefix_list_result_to_dict'),
    'cpgdata_sync_result_to_dict': ('cellpaint_pipeline.data_access', 'cpgdata_sync_result_to_dict'),
    'data_access_summary_to_dict': ('cellpaint_pipeline.data_access', 'data_access_summary_to_dict'),
    'data_download_execution_result_to_dict': ('cellpaint_pipeline.data_access', 'data_download_execution_result_to_dict'),
    'data_download_plan_to_dict': ('cellpaint_pipeline.data_access', 'data_download_plan_to_dict'),
    'data_request_to_dict': ('cellpaint_pipeline.data_access', 'data_request_to_dict'),
    'download_gallery_prefix': ('cellpaint_pipeline.data_access', 'download_gallery_prefix'),
    'download_gallery_source': ('cellpaint_pipeline.data_access', 'download_gallery_source'),
    'execute_download_plan': ('cellpaint_pipeline.data_access', 'execute_download_plan'),
    'list_cpgdata_prefixes': ('cellpaint_pipeline.data_access', 'list_cpgdata_prefixes'),
    'list_gallery_datasets': ('cellpaint_pipeline.data_access', 'list_gallery_datasets'),
    'list_gallery_prefixes': ('cellpaint_pipeline.data_access', 'list_gallery_prefixes'),
    'list_gallery_sources': ('cellpaint_pipeline.data_access', 'list_gallery_sources'),
    'list_quilt_packages': ('cellpaint_pipeline.data_access', 'list_quilt_packages'),
    'load_download_plan': ('cellpaint_pipeline.data_access', 'load_download_plan'),
    'quilt_package_browse_result_to_dict': ('cellpaint_pipeline.data_access', 'quilt_package_browse_result_to_dict'),
    'quilt_package_list_result_to_dict': ('cellpaint_pipeline.data_access', 'quilt_package_list_result_to_dict'),
    'summarize_data_access': ('cellpaint_pipeline.data_access', 'summarize_data_access'),
    'sync_cpgdata_index': ('cellpaint_pipeline.data_access', 'sync_cpgdata_index'),
    'sync_cpgdata_inventory': ('cellpaint_pipeline.data_access', 'sync_cpgdata_inventory'),
    'write_download_plan': ('cellpaint_pipeline.data_access', 'write_download_plan'),
    'run_deepprofiler_full_stack': ('cellpaint_pipeline.delivery', 'run_deepprofiler_full_stack'),
    'run_full_pipeline': ('cellpaint_pipeline.delivery', 'run_full_pipeline'),
    'run_profiling_suite': ('cellpaint_pipeline.delivery', 'run_profiling_suite'),
    'run_segmentation_bundle': ('cellpaint_pipeline.delivery', 'run_segmentation_bundle'),
    'run_segmentation_suite': ('cellpaint_pipeline.delivery', 'run_segmentation_suite'),
    'run_smoke_test': ('cellpaint_pipeline.delivery', 'run_smoke_test'),
    'available_deepprofiler_modes': ('cellpaint_pipeline.orchestration', 'available_deepprofiler_modes'),
    'end_to_end_pipeline_result_to_dict': ('cellpaint_pipeline.orchestration', 'end_to_end_pipeline_result_to_dict'),
    'resolve_segmentation_suite': ('cellpaint_pipeline.orchestration', 'resolve_segmentation_suite'),
    'run_end_to_end_pipeline': ('cellpaint_pipeline.orchestration', 'run_end_to_end_pipeline'),
    'available_mcp_tools': ('cellpaint_pipeline.mcp_tools', 'available_mcp_tools'),
    'get_mcp_tool_definition': ('cellpaint_pipeline.mcp_tools', 'get_mcp_tool_definition'),
    'mcp_tool_catalog': ('cellpaint_pipeline.mcp_tools', 'mcp_tool_catalog'),
    'mcp_tool_definition_to_dict': ('cellpaint_pipeline.mcp_tools', 'mcp_tool_definition_to_dict'),
    'run_mcp_tool': ('cellpaint_pipeline.mcp_tools', 'run_mcp_tool'),
    'run_mcp_tool_to_dict': ('cellpaint_pipeline.mcp_tools', 'run_mcp_tool_to_dict'),
    'create_mcp_server': ('cellpaint_pipeline.mcp_server', 'create_mcp_server'),
    'run_mcp_server': ('cellpaint_pipeline.mcp_server', 'run_mcp_server'),
    'PublicApiContractError': ('cellpaint_pipeline.public_api', 'PublicApiContractError'),
    'available_public_api_entrypoints': ('cellpaint_pipeline.public_api', 'available_public_api_entrypoints'),
    'available_public_api_output_contracts': ('cellpaint_pipeline.public_api', 'available_public_api_output_contracts'),
    'get_public_api_entrypoint': ('cellpaint_pipeline.public_api', 'get_public_api_entrypoint'),
    'get_public_api_output_contract': ('cellpaint_pipeline.public_api', 'get_public_api_output_contract'),
    'public_api_contract_summary': ('cellpaint_pipeline.public_api', 'public_api_contract_summary'),
    'public_api_output_contract_summary': ('cellpaint_pipeline.public_api', 'public_api_output_contract_summary'),
    'public_api_entrypoint_to_dict': ('cellpaint_pipeline.public_api', 'public_api_entrypoint_to_dict'),
    'recommended_public_api_pathways': ('cellpaint_pipeline.public_api', 'recommended_public_api_pathways'),
    'run_public_api_entrypoint': ('cellpaint_pipeline.public_api', 'run_public_api_entrypoint'),
    'run_public_api_entrypoint_to_dict': ('cellpaint_pipeline.public_api', 'run_public_api_entrypoint_to_dict'),
    'available_pipeline_presets': ('cellpaint_pipeline.presets', 'available_pipeline_presets'),
    'get_pipeline_preset_definition': ('cellpaint_pipeline.presets', 'get_pipeline_preset_definition'),
    'pipeline_preset_definition_to_dict': ('cellpaint_pipeline.presets', 'pipeline_preset_definition_to_dict'),
    'run_pipeline_preset': ('cellpaint_pipeline.presets', 'run_pipeline_preset'),
    'available_pipeline_skills': ('cellpaint_pipeline.skills', 'available_pipeline_skills'),
    'get_pipeline_skill_definition': ('cellpaint_pipeline.skills', 'get_pipeline_skill_definition'),
    'pipeline_skill_definition_to_dict': ('cellpaint_pipeline.skills', 'pipeline_skill_definition_to_dict'),
    'pipeline_skill_result_to_dict': ('cellpaint_pipeline.skills', 'pipeline_skill_result_to_dict'),
    'PipelineSkillResult': ('cellpaint_pipeline.skills', 'PipelineSkillResult'),
    'run_pipeline_skill': ('cellpaint_pipeline.skills', 'run_pipeline_skill'),
    'run_workflow': ('cellpaint_pipeline.workflows.orchestration', 'run_workflow'),
}


def __getattr__(name: str) -> Any:
    if name == '__version__':
        return __version__
    if name not in _EXPORTS:
        raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
    module_name, attr_name = _EXPORTS[name]
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
